import os
from pathlib import Path
from moviepy.editor import AudioFileClip, ImageClip

# --- CONFIGURATION ---
BASE_DIR = Path(__file__).parent
AUDIO_DIR = BASE_DIR / "episode_audio"
OUTPUT_FILE = BASE_DIR / "social_clip.mp4"

# FIXED: Pointing to PNG 
COVER_IMAGE = BASE_DIR / "cover.png" 
# NEW: Pointing to the Dynamic Card generated by generate_social.py
SOCIAL_CARD = BASE_DIR / "social_card.jpg" 

def get_latest_episode():
    # Find the latest podcast MP3
    files = sorted(list(AUDIO_DIR.glob("podcast_*.mp3")))
    if not files:
        raise FileNotFoundError("No podcast episode found in episode_audio/")
    return files[-1]

def create_hybrid_clip():
    print(" >> 🎬 STARTING VIDEO RENDER...")
    
    # 1. Load Audio
    latest_episode = get_latest_episode()
    print(f"    Using Audio: {latest_episode.name}")
    full_audio = AudioFileClip(str(latest_episode))
    
    # --- DURATION LOGIC (TEASER MODE) ---
    # Clip to 59s for Shorts/Reels/TikTok/X optimization
    target_duration = 59.0
    safe_duration = min(full_audio.duration, target_duration)
    audio_clip = full_audio.subclip(0, safe_duration)
    
    # 2. Choose Visual (Dynamic vs Static)
    if SOCIAL_CARD.exists():
        print("    ✅ Using Dynamic Social Card (Headline)")
        image_source = str(SOCIAL_CARD)
    else:
        print("    ⚠️ Social Card missing. Using generic Cover.")
        image_source = str(COVER_IMAGE)
        
    # 3. Create Video
    # No TextClip needed because SOCIAL_CARD already has text burned in
    video_clip = ImageClip(image_source).set_duration(safe_duration)
    video_clip = video_clip.set_audio(audio_clip)
    video_clip = video_clip.resize(width=1080) 
    
    # 4. Export
    print(f"    Rendering to {OUTPUT_FILE} ({safe_duration:.1f}s)...")
    video_clip.write_videofile(
        str(OUTPUT_FILE),
        fps=24,
        codec="libx264",
        audio_codec="aac",
        ffmpeg_params=["-pix_fmt", "yuv420p"] # X/Twitter Compatibility
    )
    print("    ✅ SOCIAL CLIP COMPLETE.")

if __name__ == "__main__":
    create_hybrid_clip()
