import os
import feedparser
import edge_tts
import google.generativeai as genai
import asyncio
from datetime import datetime, timezone
from email.utils import format_datetime

# --- CONFIGURATION (EDIT THIS) ---
GITHUB_USERNAME = "aisimplify333"
REPO_NAME = "daily-ai-news"
RSS_FEEDS = [
    "https://techcrunch.com/category/artificial-intelligence/feed/",
    "https://www.theverge.com/rss/artificial-intelligence/index.xml"
]
VOICE = "en-US-EricNeural"

# --- STEP 1: GET NEWS ---
def get_latest_news():
    print("Scanning the web for AI news...")
    news_items = []
    headers = {'User-Agent': 'Mozilla/5.0'} 
    for url in RSS_FEEDS:
        try:
            feed = feedparser.parse(url)
            if feed.entries:
                for entry in feed.entries[:3]:
                    news_items.append(f"- {entry.title}: {entry.summary[:200]}...")
        except:
            continue
    if not news_items: return "General AI news update."
    return "\n".join(news_items[:5])

# --- STEP 2: GET SPONSORS ---
def get_sponsors():
    try:
        with open('sponsors.json', 'r') as f: return f.read()
    except: return "No sponsors."

# --- STEP 3: GENERATE SCRIPT ---
def generate_script(news, sponsors):
    print("Connecting to AI Brain...")
    genai.configure(api_key=os.environ["GEMINI_API_KEY"])
    
    # Auto-select model
    target_model = "models/gemini-1.5-flash"
    try:
        for m in genai.list_models():
            if 'generateContent' in m.supported_generation_methods and 'gemini' in m.name:
                target_model = m.name; break
    except: pass
    
    print(f"Using Model: {target_model}")
    model = genai.GenerativeModel(target_model)
    
    prompt = f"""
    You are the host of 'AI Daily'. Today is {datetime.now().strftime('%B %d, %Y')}.
    
    News: {news}
    Sponsors: {sponsors}
    
    TASK: Write a 3-minute script.
    1. Intro: "Welcome to AI Daily for [Date]."
    2. Cover 3 news items.
    3. Insert a natural ad read for ONE sponsor.
    4. Outro.
    """
    response = model.generate_content(prompt)
    return response.text

# --- STEP 4: GENERATE AUDIO ---
async def generate_audio(text, filename):
    print(f"Synthesizing audio to {filename}...")
    communicate = edge_tts.Communicate(text, VOICE)
    await communicate.save(filename)

# --- STEP 5: UPDATE RSS FEED ---
def update_rss(audio_filename, script_summary):
    rss_file = "feed.xml"
    base_url = f"https://{GITHUB_USERNAME}.github.io/{REPO_NAME}"
    file_url = f"{base_url}/{audio_filename}"
    now = format_datetime(datetime.now(timezone.utc))
    
    # XML Template for a new item
    new_item = f"""
    <item>
      <title>AI Daily News - {datetime.now().strftime('%B %d')}</title>
      <description>{script_summary[:300]}...</description>
      <enclosure url="{file_url}" length="5000000" type="audio/mpeg"/>
      <guid>{file_url}</guid>
      <pubDate>{now}</pubDate>
    </item>
    """
    
    # Create file if it doesn't exist
    if not os.path.exists(rss_file):
        header = f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
  <channel>
    <title>AI Daily News</title>
    <description>Daily AI updates generated by AI.</description>
    <link>{base_url}</link>
    <language>en-us</language>
    <itunes:category text="Technology"/>
    </channel>
</rss>"""
        with open(rss_file, "w") as f: f.write(header)

    # Insert new item
    with open(rss_file, "r") as f: content = f.read()
    
    # Simple insertion before the placeholder or end of channel
    if "" in content:
        content = content.replace("", new_item + "\n    ")
    else:
        content = content.replace("</channel>", new_item + "\n  </channel>")
        
    with open(rss_file, "w") as f: f.write(content)
    print("RSS Feed updated successfully.")

# --- MAIN ---
if __name__ == "__main__":
    if "GEMINI_API_KEY" not in os.environ:
        print("ERROR: Run 'export GEMINI_API_KEY=...' first.")
    else:
        # 1. Generate Content
        news = get_latest_news()
        sponsors = get_sponsors()
        script = generate_script(news, sponsors)
        
        # 2. Audio Filename (Date-based)
        today_str = datetime.now().strftime('%Y-%m-%d')
        filename = f"podcast_{today_str}.mp3"
        
        # 3. Save Audio
        asyncio.run(generate_audio(script, filename))
        
        # 4. Update RSS
        update_rss(filename, script)
        print("Done! Ready to push.")
    